Lab17/Lab17/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('djangoTest/', include('djangoTest.urls')),
    path('admin/', admin.site.urls)
]

Lab17/djangoTest/urls.py
from django.urls import path
from . import views
from django.urls import include, path

app_name = 'djangoTest'
urlpatterns = [
    path('', views.index, name='index'),
    path('chefs', views.chefs, name='chefs'),
    path('posts', views.posts, name='posts'),
    path('articles', views.articles, name='articles'),
    path('ingredients', views.ingredients, name='ingredients'),
    path('recipes', views.recipes, name='recipes'),

    path('delete_chef/<int:entity_id>', views.delete_chef, name='delete_chef'),
    path('add_chef/', views.add_chef, name='add_chef'),
    path('edit_chef/', views.edit_chef, name='edit_chef'),

    path('delete_post/<int:entity_id>', views.delete_post, name='delete_post'),
    path('add_post/', views.add_post, name='add_post'),
    path('edit_post/', views.edit_post, name='edit_post'),

    path('delete_article/<int:entity_id>', views.delete_article, name='delete_article'),
    path('add_article/', views.add_article, name='add_article'),
    path('edit_article/', views.edit_article, name='edit_article'),

    path('delete_ingredient/<int:entity_id>', views.delete_ingredient, name='delete_ingredient'),
    path('add_ingredient/', views.add_ingredient, name='add_ingredient'),
    path('edit_ingredient/', views.edit_ingredient, name='edit_ingredient'),

    path('delete_recipe/<int:entity_id>', views.delete_recipe, name='delete_recipe'),
    path('add_recipe/', views.add_recipe, name='add_recipe'),
    path('edit_recipe/', views.edit_recipe, name='edit_recipe'),

    path("register", views.register_request, name="register"),
    path("login", views.login_request, name="login"),
    path("logout_req", views.logout_req, name='logout_req')
]

Lab17/djangoTest/models.py
from django.db import models


class Chef(models.Model):
    name = models.CharField(max_length=200)
    surname = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=200)
    body = models.CharField(max_length=200)

    def __str__(self):
        return self.title


class Ingredient(models.Model):
    name = models.CharField(max_length=200)
    price = models.IntegerField()

    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField(max_length=200)
    body = models.CharField(max_length=200)

    def __str__(self):
        return self.title


class Recipe(models.Model):
    title = models.CharField(max_length=200)
    body = models.CharField(max_length=200)
    cost = models.IntegerField()

    def __str__(self):
        return self.title

Lab17/djangoTest/forms.py
from django import forms

# from .models import DataOrder

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


class AccountForm(forms.Form):
    name = forms.CharField(label='Name', max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    phone = forms.CharField(label='Phone', max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.CharField(label='Email', max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))

    name.widget.attrs.update({'placeholder': 'Name'})
    phone.widget.attrs.update({'placeholder': 'Phone'})
    email.widget.attrs.update({'placeholder': 'Email'})
    name.label = ''
    phone.label = ''
    email.label = ''
    name.required = False
    phone.required = False
    email.required = False

Lab17/djangoTest/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Chef, Post, Article, Ingredient, Recipe
from django.urls import reverse
from django.shortcuts import redirect

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import login, authenticate
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import logout


def index(request):
    user = request.user
    return render(request, 'djangoTest/index.html', {'user': user})


def chefs(request):
    user = request.user
    print(user.is_authenticated)
    objs = Chef.objects.order_by('-name')
    context = {
        'objs': objs,
        'user': user,
    }
    return render(request, 'djangoTest/chefs.html', context)


def add_chef(request):
    objs = Chef.objects.order_by('-name')
    chef_id = len(objs)
    name = request.POST['first']
    surname = request.POST['last']
    entity = Chef(name=name, surname=surname)
    entity.id = chef_id  # to be able to edit entity in future
    entity.save()
    print(entity.id)
    return redirect(reverse('djangoTest:chefs'))


def delete_chef(request, entity_id):
    entity = Chef.objects.get(id=entity_id)
    entity.delete()
    return redirect(reverse('djangoTest:chefs'))


def edit_chef(request):
    entity_id = request.POST['edit_id']
    # Would be cool to check before updating but nah
    entity = Chef.objects.get(id=entity_id)
    entity.name = request.POST['edit_first']
    entity.surname = request.POST['edit_last']
    entity.save()
    return redirect(reverse('djangoTest:chefs'))


def posts(request):
    objs = Post.objects.order_by('-title')
    context = {
        'objs': objs,
    }
    return render(request, 'djangoTest/posts.html', context)


def add_post(request):
    objs = Post.objects.order_by('-title')
    entity_id = len(objs)
    title = request.POST['first']
    body = request.POST['last']
    entity = Post(title=title, body=body)
    entity.id = entity_id  # to be able to edit entity in future
    entity.save()
    return redirect(reverse('djangoTest:posts'))


def delete_post(request, entity_id):
    entity = Post.objects.get(id=entity_id)
    entity.delete()
    return redirect(reverse('djangoTest:posts'))


def edit_post(request):
    entity_id = request.POST['edit_id']
    # Would be cool to check before updating but nah
    entity = Post.objects.get(id=entity_id)
    entity.title = request.POST['edit_first']
    entity.body = request.POST['edit_last']
    entity.save()
    return redirect(reverse('djangoTest:posts'))


def articles(request):
    objs = Article.objects.order_by('-title')
    context = {
        'objs': objs,
    }
    return render(request, 'djangoTest/articles.html', context)


def add_article(request):
    objs = Article.objects.order_by('-title')
    entity_id = len(objs)
    title = request.POST['first']
    body = request.POST['last']
    entity = Article(title=title, body=body)
    entity.id = entity_id  # to be able to edit entity in future
    entity.save()
    return redirect(reverse('djangoTest:articles'))


def delete_article(request, entity_id):
    entity = Article.objects.get(id=entity_id)
    entity.delete()
    return redirect(reverse('djangoTest:articles'))


def edit_article(request):
    entity_id = request.POST['edit_id']
    # Would be cool to check before updating but nah
    entity = Article.objects.get(id=entity_id)
    entity.title = request.POST['edit_first']
    entity.body = request.POST['edit_last']
    entity.save()
    return redirect(reverse('djangoTest:articles'))


def ingredients(request):
    objs = Ingredient.objects.order_by('-name')
    context = {
        'objs': objs,
    }
    return render(request, 'djangoTest/ingredients.html', context)


def add_ingredient(request):
    objs = Ingredient.objects.order_by('-name')
    entity_id = len(objs)
    name = request.POST['first']
    cost = int(request.POST['last'])
    entity = Ingredient(name=name, cost=cost)
    entity.id = entity_id  # to be able to edit entity in future
    entity.save()
    return redirect(reverse('djangoTest:ingredients'))


def delete_ingredient(request, entity_id):
    entity = Ingredient.objects.get(id=entity_id)
    entity.delete()
    return redirect(reverse('djangoTest:ingredients'))


def edit_ingredient(request):
    entity_id = request.POST['edit_id']
    # Would be cool to check before updating but nah
    entity = Post.objects.get(id=entity_id)
    entity.name = request.POST['edit_first']
    entity.cost = int(request.POST['edit_last'])
    entity.save()
    return redirect(reverse('djangoTest:ingredients'))


def recipes(request):
    objs = Recipe.objects.order_by('-title')
    context = {
        'objs': objs,
    }
    return render(request, 'djangoTest/recipes.html', context)


def add_recipe(request):
    objs = Recipe.objects.order_by('-title')
    entity_id = len(objs)
    title = request.POST['first']
    body = request.POST['second']
    cost = request.POST['third']
    entity = Recipe(title=title, body=body, cost=cost)
    entity.id = entity_id  # to be able to edit entity in future
    entity.save()
    return redirect(reverse('djangoTest:recipes'))


def delete_recipe(request, entity_id):
    entity = Recipe.objects.get(id=entity_id)
    entity.delete()
    return redirect(reverse('djangoTest:recipes'))


def edit_recipe(request):
    entity_id = request.POST['edit_id']
    # Would be cool to check before updating but nah
    entity = Recipe.objects.get(id=entity_id)
    entity.title = request.POST['edit_first']
    entity.body = request.POST['edit_second']
    entity.cost = request.POST['edit_third']
    entity.save()
    return redirect(reverse('djangoTest:recipes'))


def logout_req(request):
    logout(request)
    messages.info(request, "You have successfully logged out.")
    return redirect(reverse("djangoTest:login"))

from django.shortcuts import render, redirect
from .forms import NewUserForm
from django.contrib.auth import login
from django.contrib import messages


def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            return redirect("djangoTest:index")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm()
    return render(request=request, template_name="djangoTest/reg/register.html", context={"register_form": form})


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("djangoTest:index")
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(request=request, template_name="djangoTest/reg/login.html", context={"login_form": form})

Lab17/templates/djangoTest/articles.html
{% extends "djangoTest/base.html" %}

{% block content %}
    <div class="header">
        <h1>Articles</h1>
        <button class="headerButton" onclick="window.location.replace('http://localhost:8000/djangoTest/');">Go Back</button>
    </div>
    {% if objs %}
        {% for entity in objs %}
            <div class="parentPostDiv">
                <div class="postDiv">
                    <div style="display: flex; justify-content: space-around">
                        <h2>{{ entity.title }}</h2>
                        <div></div><div></div><div></div><div></div>
                        <div></div><div></div><div></div><div></div>
                        <div></div><div></div><div></div><div></div>
                        <a href="delete_article/{{ entity.id }}" class="deleteSubmit">Delete</a>
                    </div>
                    <h4>{{ entity.body }}</h4>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <h1>"No articles yet."</h1>
    {% endif %}
    <div class="parentFormDiv">
        <div class="formDiv">
            <h2>New Article</h2>
            <form action="add_article/" method=post>
                {% csrf_token %}
                <label for="inputID">Title:</label>
                <input class="customInput" type="text" name="first">
                <label for="inputID">Description:</label>
                <textarea name="last" cols="40" rows="5"></textarea>
                <input class="customSubmit" type="submit" value="Save">
            </form>
        </div>
    </div>

    <div class="parentFormDiv">
        <div class="formDiv">
            <h2>Edit Article</h2>
            <form action="edit_article/" method=post>
                {% csrf_token %}
                <label for="inputID">Id:</label>
                <input class="customInput" type="text" name="edit_id">
                <label for="inputID">New Title:</label>
                <input class="customInput" type="text" name="edit_first">
                <label for="inputID">New Description:</label>
                <textarea name="edit_last" cols="40" rows="5"></textarea>
                <input class="customSubmit" type="submit" value="Save">
            </form>
        </div>
    </div>
{% endblock %}

Lab17/templates/djangoTest/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link type="text/css" rel="stylesheet" href={% static 'css/modelStyles.css' %}>
    <title>Title</title>
</head>
<body>
    {% block content %}

    {% endblock %}
</body>
</html>

Lab17/templates/djangoTest/chefs.html
{% extends "djangoTest/base.html" %}

{% block content %}
    <div class="header">
        <h1>Chefs</h1>
        <button class="headerButton" onclick="window.location.replace('http://localhost:8000/djangoTest/');">Go Back</button>
    </div>
    {% if user.is_authenticated %}
        {% if objs %}
            {% for chef in objs %}
                <div class="parentPostDiv">
                    <div class="postDiv">
                        <div style="display: flex; justify-content: space-around">
                            <h2>{{ chef.name }}</h2>
                            <div></div><div></div><div></div><div></div>
                            <div></div><div></div><div></div><div></div>
                            <div></div><div></div><div></div><div></div>
                            <a href="delete_chef/{{ chef.id }}" class="deleteSubmit">Delete</a>
                        </div>
                        <h4>{{ chef.surname }}</h4>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <h1>"No chefs yet."</h1>
        {% endif %}
        <div class="parentFormDiv">
            <div class="formDiv">
                <h2>New Chef</h2>
                <form action="add_chef/" method=post>
                    {% csrf_token %}
                    <label for="inputID">Name:</label>
                    <input class="customInput" type="text" name="first">
                    <label for="inputID">Surname:</label>
                    <input class="customInput" type="text" name="last">
                    <input class="customSubmit" type="submit" value="Save">
                </form>
            </div>
        </div>

        <div class="parentFormDiv">
            <div class="formDiv">
                <h2>Edit Chef</h2>
                <form action="edit_chef/" method=post>
                    {% csrf_token %}
                    <label for="inputID">Old name:</label>
                    <input class="customInput" type="text" name="edit_id">
                    <label for="inputID">New Name:</label>
                    <input class="customInput" type="text" name="edit_first">
                    <label for="inputID">New Surname:</label>
                    <input class="customInput" type="text" name="edit_last">
                    <input class="customSubmit" type="submit" value="Save">
                </form>
            </div>
        </div>
    {% endif %}
{% endblock %}

Lab17/templates/djangoTest/header.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <link type="text/css" rel="stylesheet" href={% static 'css/modelStyles.css' %}>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Title</title>
  </head>
 <body>

    {% block content %}

    {% endblock %}

  </body>
</html>

Lab17/templates/djangoTest/index.html
{% extends "djangoTest/base.html" %}

{% block content %}

<form action="{% url 'djangoTest:chefs' %}" method="post">
    {% csrf_token %}
    <input class="customInput" type="submit" value="Chefs">
</form>

<form action="{% url 'djangoTest:recipes' %}" method="post">
    {% csrf_token %}
    <input class="customInput" type="submit" value="Recipes">
</form>

<form action="{% url 'djangoTest:ingredients' %}" method="post">
    {% csrf_token %}
    <input class="customInput" type="submit" value="Ingredients">
</form>

<form action="{% url 'djangoTest:posts' %}" method="post">
    {% csrf_token %}
    <input class="customInput" type="submit" value="Posts">
</form>

<form action="{% url 'djangoTest:articles' %}" method="post">
    {% csrf_token %}
    <input class="customInput" type="submit" value="Articles">
</form>

{% if user.is_authenticated %}
    <form action="{% url 'djangoTest:logout_req' %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Logout">
    </form>
{% endif %}

{% endblock %}

Lab17/templates/djangoTest/ingredients.html
{% extends "djangoTest/base.html" %}

{% block content %}
    <div class="header">
        <h1>Ingredients</h1>
        <button class="headerButton" onclick="window.location.replace('http://localhost:8000/djangoTest/');">Go Back</button>
    </div>
    {% if objs %}
        {% for entity in objs %}
            <div class="parentPostDiv">
                <div class="postDiv">
                    <div style="display: flex; justify-content: space-around">
                        <h2>{{ entity.name }}</h2>
                        <div></div><div></div><div></div><div></div>
                        <div></div><div></div><div></div><div></div>
                        <div></div><div></div><div></div><div></div>
                        <a href="delete_ingredient/{{ entity.id }}" class="deleteSubmit">Delete</a>
                    </div>
                    <h4>{{ entity.cost }}</h4>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <h1>"No ingredients yet."</h1>
    {% endif %}
    <div class="parentFormDiv">
        <div class="formDiv">
            <h2>New Ingredient</h2>
            <form action="add_ingredient/" method=post>
                {% csrf_token %}
                <label for="inputID">Name:</label>
                <input class="customInput" type="text" name="first">
                <label for="inputID">Cost:</label>
                <input class="customInput" type="text" name="last">
                <input class="customSubmit" type="submit" value="Save">
            </form>
        </div>
    </div>

    <div class="parentFormDiv">
        <div class="formDiv">
            <h2>Edit Ingredient</h2>
            <form action="edit_ingredient/" method=post>
                {% csrf_token %}
                <label for="inputID">Id:</label>
                <input class="customInput" type="text" name="edit_id">
                <label for="inputID">New Name:</label>
                <input class="customInput" type="text" name="edit_first">
                <label for="inputID">New Cost:</label>
                <input class="customInput" type="text" name="edit_last">
                <input class="customSubmit" type="submit" value="Save">
            </form>
        </div>
    </div>
{% endblock %}

Lab17/templates/djangoTest/posts.html
{% extends "djangoTest/base.html" %}

{% block content %}
    <div class="header">
        <h1>Posts</h1>
        <button class="headerButton" onclick="window.location.replace('http://localhost:8000/djangoTest/');">Go Back</button>
    </div>
    {% if objs %}
        {% for post in objs %}
            <div class="parentPostDiv">
                <div class="postDiv">
                    <div style="display: flex; justify-content: space-around">
                        <h2>{{ post.title }}</h2>
                        <div></div><div></div><div></div><div></div>
                        <div></div><div></div><div></div><div></div>
                        <div></div><div></div><div></div><div></div>
                        <a href="delete_post/{{ post.id }}" class="deleteSubmit">Delete</a>
                    </div>
                    <h4>{{ post.body }}</h4>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <h1>"No posts yet."</h1>
    {% endif %}
    <div class="parentFormDiv">
        <div class="formDiv">
            <h2>New Post</h2>
            <form action="add_post/" method=post>
                {% csrf_token %}
                <label for="inputID">Title:</label>
                <input class="customInput" type="text" name="first">
                <label for="inputID">What's New:</label>
                <textarea name="last" cols="40" rows="5"></textarea>
                <input class="customSubmit" type="submit" value="Save">
            </form>
        </div>
    </div>

    <div class="parentFormDiv">
        <div class="formDiv">
            <h2>Edit Post</h2>
            <form action="edit_post/" method=post>
                {% csrf_token %}
                <label for="inputID">Id:</label>
                <input class="customInput" type="text" name="edit_id">
                <label for="inputID">New Title:</label>
                <input class="customInput" type="text" name="edit_first">
                <label for="inputID">New Description:</label>
                <textarea name="edit_last" cols="40" rows="5"></textarea>
                <input class="customSubmit" type="submit" value="Save">
            </form>
        </div>
    </div>
{% endblock %}

Lab17/templates/djangoTest/recipes.html
{% extends "djangoTest/base.html" %}

{% block content %}
    <div class="header">
        <h1>Recipes</h1>
        <button class="headerButton" onclick="window.location.replace('http://localhost:8000/djangoTest/');">Go Back</button>
    </div>
    {% if objs %}
        {% for entity in objs %}
            <div class="parentPostDiv">
                <div class="postDiv">
                    <div style="display: flex; justify-content: space-around">
                        <h2>{{ entity.title }}</h2>
                        <div></div><div></div><div></div><div></div>
                        <div></div><div></div><div></div><div></div>
                        <div></div><div></div><div></div><div></div>
                        <a href="delete_recipe/{{ entity.id }}" class="deleteSubmit">Delete</a>
                    </div>
                    <h4>{{ entity.body }}</h4>
                    <h4>Cost: {{ entity.cost }}</h4>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <h1>"No recipes yet."</h1>
    {% endif %}
    <div class="parentFormDiv">
        <div class="formDiv">
            <h2>New Recipe</h2>
            <form action="add_recipe/" method=post>
                {% csrf_token %}
                <label for="inputID">Title:</label>
                <input class="customInput" type="text" name="first">
                <label for="inputID">Description:</label>
                <textarea name="second" cols="40" rows="5"></textarea>
                <label for="inputID">Cost:</label>
                <input class="customInput" type="text" name="third">
                <input class="customSubmit" type="submit" value="Save">
            </form>
        </div>
    </div>

    <div class="parentFormDiv">
        <div class="formDiv">
            <h2>Edit Recipe</h2>
            <form action="edit_recipe/" method=post>
                {% csrf_token %}
                <label for="inputID">Id:</label>
                <input class="customInput" type="text" name="edit_id">
                <label for="inputID">New Title:</label>
                <input class="customInput" type="text" name="edit_first">
                <label for="textfield_edit">New Description:</label>
                <textarea id="textfield_edit" name="edit_second" cols="40" rows="5"></textarea>
                <label for="edit_cost">New Cost:</label>
                <input id="edit_cost" class="customInput" type="text" name="edit_third">
                <input class="customSubmit" type="submit" value="Save">
            </form>
        </div>
    </div>
{% endblock %}